# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# User specific aliases and functions
echo "
# ./snic.sh -silent -responseFile /tmp/my_response_file.txt
# /mnt/ses_11_2_2_2_0_linux64/runInstaller

"

